Document: brew-meta-itsecurity
Title: Debian brew-meta-itsecurity Manual
Author: <insert document author here>
Abstract: This manual describes what brew-meta-itsecurity is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/brew-meta-itsecurity/brew-meta-itsecurity.sgml.gz

Format: postscript
Files: /usr/share/doc/brew-meta-itsecurity/brew-meta-itsecurity.ps.gz

Format: text
Files: /usr/share/doc/brew-meta-itsecurity/brew-meta-itsecurity.text.gz

Format: HTML
Index: /usr/share/doc/brew-meta-itsecurity/html/index.html
Files: /usr/share/doc/brew-meta-itsecurity/html/*.html
